mondoohq/packer-plugin-cnspec

test/hcl-docker/docker-ubuntu.pkr.hcl
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> ⭐️ use packer init in demo

provisioner/buildinfo.go, provisioner/buildinfo_test.go
Signed-off-by: Preslav <preslav@mondoo.com>
=> 🐛 Fix SshPrivateKey json naming and extend tests.

.github/actions/spelling/expect.txt, README.md
=> Adds link to tutorial and general updates to README

provisioner/provisioner.hcl2spec.go
Adds the updated provisioner hcl2spec.
=> 🧹 Add updated hcl2spec.

README.md, examples/packer-aws/ubuntu-2004.pkr.hcl, examples/packer-aws/ubuntu-2204.pkr.hcl, examples/packer-aws/windows-2019.pkr.hcl, examples/packer-gcp/ubuntu2004.pkr.hcl
updates template image_prefix
Renames template and updates plugin version
=> Adds example template for GCP image

download.sh
Hi
Thanks for the original script, I've made a few amendments.
Added a couple of error handling switches, as I missed having jq installed first time round and the script carried on, it should error and stop now.
After that I've added a step to download and validate the checksum of the archive.
Best Regards
Gary
Signed-off-by: Gary Bright <digitalgaz@hotmail.com>
=> Added a step to validate the archive checksum

.github/dependabot.yml, .github/workflows/test-plugin.yml, .gitignore, .goreleaser.yml, Makefile, docs-partials/provisioner/Config-not-required.mdx, docs-partials/provisioner/SudoConfig-not-required.mdx, docs/mondoo.mdx, provisioner/provisioner.go
THIS IS A DRAFT PR. DO NOT MERGE UNTIL REVIEWED. NEEDS WORK
=> Adds configuration to build docs and publish on packer.io

docs/provisioners/mondoo.mdx
Signed-off-by: Preslav <preslav@mondoo.com>
=> Add link to gcp tutorial in mondoo.mdx.

.github/actions/spelling/expect.txt, README.md
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>
=> ⭐️ add new github community to readme

.github/actions/spelling/expect.txt, examples/packer-vsphere/rocky8/README.md, examples/packer-vsphere/rocky8/data/ks.pkrtpl.hcl, examples/packer-vsphere/rocky8/rocky-8.auto.pkrvars.hcl, examples/packer-vsphere/rocky8/rocky-8.pkr.hcl, examples/packer-vsphere/rocky8/variables.pkr.hcl, examples/packer-vsphere/rocky8/variables.pkrvars.hcl
This adds a rocky 8 build example for vsphere to the examples
=> ⭐️ Rocky Linux 8 VMware vSphere example

provisioner/provisioner.go
1. prefer MONDOO_CONFIG_PATH
2. if config is set in hcl use that value
3. if no config is set load config from home or system directory
=> 🧹 fine-tune config loading

.github/dependabot.yml
Signed-off-by: Christian Zunker <christian@mondoo.com>
=> 🧹 Add GHA to dependabot

.goreleaser.yml
we had arm builds but somehow packer download the non 64 bit arm binary
fixes #88
=> ⭐️ add arm builds for linux

README.md
fix link to policy scoring documentation
https://github.com/mondoohq/packer-plugin-cnspec/issues/97
=> fix link to policy scoring

.github/workflows/pr-test-lint.yaml, .github/workflows/release.yaml, examples/custom-policybundle/README.md, examples/custom-policybundle/custom-policy.mql.yaml, examples/custom-policybundle/docker-ubuntu.pkr.hcl, provisioner/provisioner.go
fixes https://github.com/mondoohq/packer-plugin-cnspec/issues/101
=> 🐛 fix loading local policy bundles

README.md, examples/github-actions/packer-build-scan.yaml, examples/packer-aws/amazon-linux-2.pkr.hcl
=> ⭐️ Adds GitHub Actions example

.github/workflows/pr-test-lint.yaml
This fixes workflows for pushes.
=> 🐛 Fix PR testing

examples/packer-vsphere/photon4/data/ks.pkrtpl.hcl, examples/packer-vsphere/photon4/photon.auto.pkrvars.hcl, examples/packer-vsphere/photon4/photon.pkr.hcl
Added a provisioner to patch the template, needed to pass Platform Vulnerability Policy.
Added a provisioner to amend the sshd_config and reboot the template before the cnspec scan.
=> ⭐️ Updated packer-vSphere photon 4 Example

README.md
Updates readme.md for style, clarity, updated URLs, etc.
=> 📄  Edits readme

.github/env, .github/workflows/ensure-generated.yaml, .github/workflows/notify-integration-release-via-manual.yaml, .github/workflows/notify-integration-release-via-tag.yaml
- update go version for pipeline
- new check for generated content
=> 🧹 update gh flow and ensure the same go version for all jobs

.web-docs/README.md, README.md, docs/README.md, examples/custom-policybundle/docker-ubuntu.pkr.hcl, examples/packer-aws/amazon-linux-2023.pkr.hcl, examples/packer-aws/ubuntu-2004.pkr.hcl, examples/packer-aws/ubuntu-2204.pkr.hcl, examples/packer-aws/windows-2019.pkr.hcl, examples/packer-docker/docker-ubuntu.pkr.hcl, examples/packer-gcp/ubuntu2004.pkr.hcl, examples/packer-vsphere/centos7/centos-7-x86_64.vsphere.pkr.hcl, examples/packer-vsphere/rocky8/rocky-8.pkr.hcl, test/hcl-docker/docker-ubuntu.pkr.hcl, test/hcl-vmware-arm/alpine.pkr.hcl
This PR updates all templates and tests to use the new v10 release.
=> Updates example templates and tests to v10

examples/docker/docker-ubuntu.pkr.hcl
=> 🧹 extend docker example with annotations

.github/pr-body.md, .github/workflows/cnspec-update.yml
This workflow will be triggered by the cnspec repo on release.
=> ✨ Create PR to bump cnspec

version/version.go
fixes https://github.com/mondoohq/packer-plugin-cnspec/issues/208
=> 🐛 fix packer internal version

go.mod, go.sum, provisioner/provisioner.go
fixes https://github.com/mondoohq/packer-plugin-cnspec/issues/207
=> 🧹 update the provider when its outdated

examples/aws/amazon-linux-2.pkr.hcl, examples/aws/amazon-linux-2023.pkr.hcl, examples/aws/ubuntu-2004.pkr.hcl, examples/aws/ubuntu-2204.pkr.hcl, examples/aws/windows-2019.pkr.hcl, examples/azure/windows/windows.pkr.hcl, examples/custom-policybundle/docker-ubuntu.pkr.hcl, examples/docker/docker-ubuntu.pkr.hcl, examples/gcp/ubuntu2004.pkr.hcl, examples/vsphere/centos7/centos-7-x86_64.vsphere.pkr.hcl, examples/vsphere/rocky8/rocky-8.pkr.hcl
Updates all examples to use cnspec:11
=> Updates examples to use cnspec11

.github/workflows/pr-test-lint.yaml, .github/workflows/release.yaml
https://goreleaser.com/deprecations/\#-skip
https://goreleaser.com/deprecations/\#-rm-dist
=> 🐛 Fix removed goreleaser switches

.github/workflows/gh-release.yaml
We need to add the correct secret to make this work.
So, do not trigger it for now, but prepare it for testing.
=> 🧹 Disable GH auto release for now

.github/workflows/pr-test-lint.yaml
Porting over the changes we did in the cnspec repo:
https://github.com/mondoohq/cnspec/blob/main/.github/workflows/pr-test-lint.yml#L138-L151
=> 🤖 Auto approve cnspec bump PRs

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/reject.txt
=> Pull in the latest spellcheck config

.github/workflows/gh-release.yaml
=> 🐛 Fix Slack notification color

.web-docs/README.md, .web-docs/components/provisioner/cnspec/README.md, .web-docs/components/provisioner/mondoo/README.md, README.md, docs/README.md, docs/provisioners/cnspec.mdx, docs/provisioners/mondoo.mdx
Simplifies the readme and uses the official packer documentation.
=> 🧹 update readme

provisioner/provisioner.go
https://github.com/mondoohq/packer-plugin-cnspec/actions/runs/15417166806/job/43382597264\?pr\=410
=> 🧹 Prevent linter warnings
