- provisioner.go
The json format files do not use annotations and trying to merge the labels in there crashes the provisioner.
> 🐛 Initialize annotations map if not specified.

- examples/packer-aws/amazon-linux-2.pkr.hcl
- examples/packer-aws/ubuntu-2004.pkr.hcl
- examples/packer-aws/windows-2019.pkr.hcl
A quick change to make `AWS_PROFILE` a variable.
> Updates examples to make aws profile a var

- .goreleaser.yml
- Makefile
- provisioner/provisioner.go
I noticed during testing that the mondoo version and build are empty:
`==> amazon-ebs: Running mondoo (Version: , Build: )`
I added a `build/prod` make job that correctly assigns the values after which this gets fixed.
`==> amazon-ebs: Running Mondoo packer provisioner (Version: v0.2.1, Build: af68414)`
I am not sure on the release process and what needs to be changed there, could use some help if this PR gets approved
> ⭐Add a prod build make job.

- .github/actions/spelling/expect.txt
- README.md
- examples/packer-aws/amazon-linux-2.json
- examples/packer-aws/amazon-linux-2.pkr.hcl
- examples/packer-aws/ubuntu-18.04.json
- examples/packer-aws/ubuntu-20.04.json
- examples/packer-aws/ubuntu-2004.pkr.hcl
- examples/packer-aws/windows-2019.pkr.hcl
- provisioner/provisioner.go
We don't have the option to specify a Mondoo config, can be used to scan against a different space for example.
Also bumped the required plugin version to 0.3.0
> ⭐ Add option to set mondoo config path via vars

- examples/packer-aws/amazon-linux-2.pkr.hcl
Hasn't been committed in the last PR, so a quick fix here
> Bump mondoo plugin version in amazon-linux-2 example.

- examples/packer-aws/amazon-linux-2.json
- examples/packer-aws/amazon-linux-2.pkr.hcl
- examples/packer-aws/ubuntu-18.04.json
- examples/packer-aws/ubuntu-20.04.json
- examples/packer-aws/ubuntu-2004.pkr.hcl
- examples/packer-aws/ubuntu-2204.pkr.hcl
- examples/packer-aws/windows-2019.pkr.hcl
This PR removes the `AWS_PROFILE` environment variable from the AWS example templates. 
Closes https://github.com/mondoohq/packer-plugin-mondoo/issues/14
> Removes AWS_PROFILE env var from example templates

- docs/provisioners/index.mdx
- docs/provisioners/mondoo.mdx
The Packer plugin ingestion pipeline for remote docs requires the plugin
documentation be in a specific format/directory to ensure the correct documentation is being ingested.
This change move the documentation into a component type directory under the top-level docs directory, and splits the single documentation file into two separate files:
a plugin overview file (docs/provisioners/index.mdx),  and a provisioner specific file (docs/provisioner/mondoo.mdx).
> Update provisioner docs

- provisioner/provisioner.go
Fixes #40 by explicitly passing the private key file and/or passwords to Mondoo.
> 🐛 Fix provisioner ignoring identity file and passwords when using ss

- go.mod
- go.sum
Scanning hcl files panics, see https://github.com/zclconf/go-cty/issues/134 for context.
We should avoid upgrading that specific module until it's resolved
> 🐛 Downgrade zclconf/go-cty to v1.10.0

- .goreleaser.yml
creates two archives instead one for different builds
> 🐛 build two archives for the builds

- README.md
- docs/provisioners/cnspec.mdx
- docs/provisioners/mondoo.mdx
Updates repo README. Adds cnspec directory listing on Hashi plugin site. Deprecates mondoo plugin directory listing.
> Updates README HashiCorp plugin directory docs

- .gitignore
- .goreleaser.yml
- Makefile
- README.md
- docs/provisioners/mondoo.mdx
- download.sh
- go.mod
- main.go
- provisioner/provisioner.go
This PR changes the go module name to `packer-plugin-cnspec`
> 🧹 rename go package to packer-plugin-cnspec

- .github/workflows/build.yml
reduces the github action time when no code was changed
> 🧹 only build go app if the files have been changed

- provisioner/provisioner.go
prints debug logging even when no error happened during scan
> 🧹 always print debug log when debugging is enabled

- docs/provisioners/mondoo.mdx
It looks like the URL to the cnspec provisioner is no longer accurate, as HashiCorp made some changes on their side.  This fixes that!
> Update mondoo.mdx - Fix cnspec provisioner link

- go.mod
- go.sum
Implemented the recommended changes for packer sdk 0.5.1 as described in https://github.com/hashicorp/packer-plugin-sdk/issues/187#user-content-available-fixes.
To avoid compile issues, I also downgraded hcl to v2.16.2 which is the same as packer sdk is using https://github.com/hashicorp/packer-plugin-sdk/blob/main/go.mod#L41
> 🧹 use go packages recommended by packer sdk

- Makefile
This sets the version to the imported module version. This version is displayed with mondoo.version.
Fixes #139
> 🧹 Set cnquery version

- .github/workflows/release.yaml
- .goreleaser.yml
This sets the version to the imported module version. This version is displayed with mondoo.version.
Fixes #139 for goreleaser
> 🧹 Set cnquery version for goreleaser

- examples/packer-docker/docker-ubuntu.pkr.hcl
- provisioner/provisioner.go
> 🧹 Try to update os provider to latest

- .copywrite.hcl
- examples/packer-vsphere/photon4/data/ks.pkrtpl.hcl
- examples/packer-vsphere/photon4/photon.pkr.hcl
Adding copyright header into hcl templates renders the data wrong for the machines and it leads to errors.
> 🧹 do not apply copyright header for hcl terraform templates

- provisioner/provisioner.go
This is also fixed upstream for future versions https://github.com/mondoohq/cnquery/pull/2858
> 🐛 explicitly set sudo executable when sudo is activated

- .github/dependabot.yml
requires #174 to be merged to turn green
> 🧹 update dependabot configuration

- .copywrite.hcl
- .web-docs/components/provisioner/cnspec/README.md
- .web-docs/components/provisioner/mondoo/README.md
- docs-partials/provisioner/Config-not-required.mdx
- provisioner/provisioner.go
- provisioner/provisioner.hcl2spec.go
> 🧹 update packer parameter descriptions

- .goreleaser.yml
- .web-docs/components/provisioner/cnspec/README.md
- .web-docs/components/provisioner/mondoo/README.md
- README.md
- docs-partials/provisioner/Config-not-required.mdx
- examples/packer-docker/docker-ubuntu.pkr.hcl
- provisioner/provisioner.go
- provisioner/provisioner.hcl2spec.go
after #175
fixes https://github.com/mondoohq/packer-plugin-cnspec/issues/98
The following configuration shows how to set the output format to JUnit and the output target to `test-results.xml`:
```hcl
provisioner "cnspec" {
on_failure = "continue"
output = "junit"
output_target = "test-results.xml"
}
```
> ⭐️ support writing reports to file

- .goreleaser.yml
Followup https://github.com/mondoohq/packer-plugin-cnspec/pull/153/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L62-L65
> 🧹 docs.zip is not needed anymore

- examples/azure/windows/README.md
- examples/azure/windows/variables.pkrvars.hcl
- examples/azure/windows/windows.pkr.hcl
This adds a test example for Azure ARM. The example is heavily based on the information provided by @javier-glez in #181. Thank you!
> ⭐️ add azure windows build example

- provisioner/provisioner.go
@scottford-io reported that we install to many provider with the packer plugin. Indeed that is not required. We can just focus on ensuring the os provider is installed.
> 🧹 ensure os provider is installed

- provisioner/provisioner.go
This change ensure the plugin does not panic when we have not returned a proper result. This case should normally not happen. Therefore it does not fix the underlying issue. cnspec is expected to always return a report or an error.
related to #187
> 🧹 handle case where no report in returned

- provisioner/provisioner.go
This change prints a proper formatted json in packer cli output and also generates a local inventory file. This makes testing a lot easier for cases where we need to investigate connection issues.
> 🧹 improve debug output of scan job

- provisioner/provisioner.go
depends on https://github.com/mondoohq/cnquery/pull/3137
In case the cnspec runtime crashes, the provider also crashes. Problem is that it is quite difficult to see which crash happened. This makes it very difficult for users to report the panic. This uses the new cnquery panic handler and also prints the panic in the cli output.
> panic handler for provision step

- provisioner/provisioner.go
This fixes #187
When users used an aws setup with ssh agent authentication the provider could not connect to the remote machine.
```
source "amazon-ebs" "ubuntu2204" {
ami_name      = "${var.image_prefix}-${local.timestamp}"
instance_type = "t2.micro"
region        = var.aws_region
source_ami_filter {
filters = {
name                = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"
root-device-type    = "ebs"
virtualization-type = "hvm"
}
most_recent = true
owners      = ["099720109477"]
}
ssh_username = "ubuntu"
ssh_keypair_name = "chris-rock"
ssh_agent_auth   = true
}
```
> ⭐️ support ssh agent authentication

- Makefile
Ensure we use a `-` instead of a `+`. If the tag has a `+` that would mean the version has two of those and packer does not like that
> 🧹 Fix version generation in Makefile.

- examples/vsphere/rocky8/data/ks.pkrtpl.hcl
- examples/vsphere/rocky8/rocky-8.pkr.hcl
We experienced some issues where two builds of the cnspec provisioner update same asset in Mondoo platform. This is caused by the fact that two builds have the same hostname. Therefore users should make sure that different builds get different hostnames. In our rocky example for vsphree we explicitly set the hostname for the build.
> 🧹 set hostname for rocky

- .copywrite.hcl
- LICENSE
> Update copyright dates to 2024

- .github/workflows/cnspec-update.yml
- .github/workflows/gh-release.yaml
The idea is:
- When we merge a cnspec version bump PR, it updates the VERSION file in merge
- The new workflow triggers and creates the GH release (currently we do this manually)
- This will trigger the actual release builds and publishes
For now, this creates releases as drafts. When the releases are ok, we can remove the draft flag.
> 🤖 Automatically create GH release after cnspec bump

- .github/workflows/gh-release.yaml
It worked in yesterdays release:
https://github.com/mondoohq/packer-plugin-cnspec/pull/257
I only needed to confirm the release. Let's automate this and we can use the pattern also in other repos.
> 🤖 Un-draft GH releases

- .github/workflows/gh-release.yaml
This is another try on automatically creating the plugin releases when we update cnspec.
> 🤖 Use app token for automatic releases

- .github/workflows/pr-test-lint.yaml
When we auto approve these, this will automatically trigger the release workflow. This will allow us to create a packer-plugin release each time we create a new cnspec release.
> 🤖 Auto approve cnspec bump PRs

- .github/workflows/pr-test-lint.yaml
Tha approval was skipped: https://github.com/mondoohq/packer-plugin-cnspec/actions/runs/11793691547/job/32849991279
Part of the event:
```
"event": {
"after": "5d3ee94a90fec6e939a036d9f84cd7545ae345c1",
"base_ref": null,
"before": "0000000000000000000000000000000000000000",
"commits": [
{
"author": {
"email": "tools@mondoo.com",
"name": "Mondoo Tools",
"username": "mondoo-tools"
},
"committer": {
"email": "tools@mondoo.com",
"name": "Mondoo Tools",
"username": "mondoo-tools"
},
"distinct": true,
"id": "5d3ee94a90fec6e939a036d9f84cd7545ae345c1",
"message": "🧹 Bump cnspec to v11.30.0",
"timestamp": "2024-11-12T08:45:45Z",
"tree_id": "168e5c55bb8d1d6d24143c77c5e20cb2fdb8d145",
"url": "https://github.com/mondoohq/packer-plugin-cnspec/commit/5d3ee94a90fec6e939a036d9f84cd7545ae345c1"
}
],
... …
```
> 🐛 Fix the field that is checked for 'mondoo-tools'

- .github/workflows/ensure-generated.yaml
1. There is no need to specify `shell: bash`, for `ubuntu-*`, it is the default
2. There is no need for two unnamed steps, so they've been merged into one
> Simplify `ensure-generated` workflow

- .golangci.yml
This fixes https://github.com/mondoohq/packer-plugin-cnspec/actions/runs/13921192786/job/38954630816\?pr\=381
Same as https://github.com/mondoohq/cnspec/pull/1604
> 🧹 Fix deprecated/removed/moved parameters for golangci

- .golangci.yml
That should fix: https://github.com/mondoohq/packer-plugin-cnspec/actions/runs/15414446483/job/43373844286
> 🧹 Bump golang-lint config version

- .github/env
- go.mod
Required for https://github.com/mondoohq/packer-plugin-cnspec/actions/runs/18309104157/job/52133291484
> 🧹 Bump go to v1.25
